import tkinter as tk
import os
os .system('echo off')
reg_window = tk.Tk()
reg_window.title('注册/登陆您的账户')
first_lable = tk.Label(reg_window,text='请输入您的用户名和密码')
first_lable.pack()
get_input1 = tk.StringVar()
get_input2 = tk.StringVar()
get_input3 = tk.StringVar()
get_input4 = tk.StringVar()
get_input5 = tk.StringVar()
get_input6 = tk.StringVar()
get_input7 = tk.StringVar()
name_lable = tk.Label(reg_window,text='通用用户名:')
Entry_name = tk.Entry(reg_window,textvariable=get_input1)
name_lable.pack()
Entry_name.pack()
pswd_lable = tk.Label(reg_window,text='通用密码:')
Entry_pswd = tk.Entry(reg_window,textvariable=get_input2)
pswd_lable.pack()
Entry_pswd.pack()
ip_lable = tk.Label(reg_window,text='MySQL数据库IP地址:')
Entry_ip = tk.Entry(reg_window,textvariable=get_input3)
ip_lable.pack()
Entry_ip.pack()
port_lable = tk.Label(reg_window,text='端口:')
Entry_port = tk.Entry(reg_window,textvariable=get_input4)
port_lable.pack()
Entry_port.pack()
box_lable = tk.Label(reg_window,text='库名:')
Entry_box = tk.Entry(reg_window,textvariable=get_input5)
box_lable.pack()
Entry_box.pack()
word_lable = tk.Label(reg_window,text='编码:')
Entry_word = tk.Entry(reg_window,textvariable=get_input6)
word_lable.pack()
Entry_word.pack()
big_name_lable = tk.Label(reg_window,text='用户实名:')
Entry_big_name = tk.Entry(reg_window,textvariable=get_input7)
big_name_lable.pack()
Entry_big_name.pack()
run_next = tk.Button(reg_window,text='register',command=reg_window.quit)
run_next.pack()
bad_ball = tk.Label(reg_window,text='请尽量减少外出')
bad_ball.pack()
reg_window.geometry('450x400')
reg_window.mainloop()